title: Warum
email: luis.luethi@students.fhnw.ch
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

markdown: kramdown
#theme: minima

collections:
    projekte:
        output: true #generiert html-seite
        permalink: /projekte/:path/ #pfad für jede neue seite
    projekte_einzeln:
        output: true
        permalink: /projekte/:path/
#defaults: #default layout
#    scope:
#        type: projekte
#    values:
#        layout: projekt #sucht im ordner _layout nach projekt.html
